orphanRemoval = true was giving me an error when I edited a Post.
org.hibernate.HibernateException: A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: com.codeup.blog.springbootblog.Models.Post.votes

removed it for now